# Generated by Django 2.0.5 on 2018-06-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180618_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxusertoken',
            name='accessToken',
            field=models.CharField(default='', max_length=512),
        ),
    ]
