# Generated by Django 2.0.5 on 2018-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180619_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxusertoken',
            name='account_id',
            field=models.TextField(default='', max_length=512),
        ),
    ]
