"""
Django settings for dropboxapp project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_URL = "https://b37feff3.ngrok.io"

### YellowAnt OAuth specific settings ###

YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YA_APP_ID = "1911"

YELLOWANT_CLIENT_ID = "i1Vl0zyRTfWHhXdXWGGQMQ0JjyxiBYZbRGQxlgmD"
YELLOWANT_CLIENT_SECRET = "FwFhJ3N3X7H9ss1gfpD6b8a1Wu4Xj06HwGjErDSIyied2CU6vKxXTWwTdU1NJc6tlEru0ozt5tW2CV5eSA6seu7A4DQzTxvMehv5E54Fs8nBqbAkRuOwU4X7bJfdFO5x"
YELLOWANT_VERIFICATION_TOKEN = "AmD4fo8oNysRmcyoCPPmmEMJgHhJb1AkQjBd2h6X5y6YDHvJiyf3ie81doyjASxY9ZYMg5SSWI8fPBDjWMofZ7ayyC9V9a2jLPtMVwnP9WqVVTyZxqWFHerohzepUEm1"
YELLOWANT_REDIRECT_URL = BASE_URL + "/yellowantredirecturl/"

# Dropbox Settings

DROPBOX_CLIENT_ID = "pf80f4dqnufmysv"
DROPBOX_CLIENT_SECRET = "jxd29kygpjfd2uk"
DROPBOX_REDIRECT_URL = BASE_URL + "/dropbox-redirect-url/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@+=k_h_-(yp0k&i17g0jsbbeof91)@n_3x+cf)dalp^&&2k-^r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'web',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'records'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dropboxapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dropboxapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dropboxdb',
        'USER': 'root',
        'PASSWORD': 'vimal_1996',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
